version: '3.8'

services:
  # Base de données relationnelle et vectorielle
  postgres:
    image: pgvector/pgvector:0.7.0-pg16
    container_name: trustai-postgres
    environment:
      POSTGRES_USER: trustai_user
      POSTGRES_PASSWORD: trustai_password
      POSTGRES_DB: trustaidb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trustai-network
    restart: unless-stopped

  # Message Broker (Apache Kafka en mode KRaft)
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: trustai-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - trustai-network
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: trustai-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/trustaidb
      KC_DB_USERNAME: trustai_user
      KC_DB_PASSWORD: trustai_password
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - trustai-network
    restart: unless-stopped

volumes:
  postgres_data:
  keycloak_data:

networks:
  trustai-network:
    driver: bridge