server:
  port: 8082

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: rag-service
  datasource:
    url: jdbc:postgresql://localhost:5432/trustaidb
    username: trustai_user
    password: trustai_password
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/trustai-realm

openai:
  api:
    key: "sk-dummy-key"
