server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        # Route d'exemple pour tester le fonctionnement du Gateway vers un service externe (ex: HTTPBin)
        - id: test_route
          uri: https://httpbin.org
          predicates:
            - Path=/get

management:
  endpoints:
    web:
      exposure:
        include: health, info